In [2]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [9]:
torch.randn(5, 3)

tensor([[ 0.9660, -0.4475, -0.8014],
        [ 1.8941,  0.8553, -1.2963],
        [ 1.3430, -0.3306, -1.0483],
        [ 0.3871, -0.4256,  0.3176],
        [ 0.3380, -0.5692, -1.6609]])

In [7]:
z

tensor([-1.0809,  2.4346, -3.8777], grad_fn=<AddBackward0>)

In [4]:
y

tensor([0., 0., 0.])

In [5]:
w

tensor([[-1.6100, -0.8773,  0.5627],
        [-1.6658,  1.1390, -3.4155],
        [ 0.0907,  0.4359, -0.4352],
        [ 0.7896,  0.7700,  1.0447],
        [ 1.1282,  0.9367, -1.6566]], requires_grad=True)

In [2]:
loss

tensor(1.8739, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [11]:
w

tensor([[-1.6100, -0.8773,  0.5627],
        [-1.6658,  1.1390, -3.4155],
        [ 0.0907,  0.4359, -0.4352],
        [ 0.7896,  0.7700,  1.0447],
        [ 1.1282,  0.9367, -1.6566]], requires_grad=True)

In [10]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0844, 0.3065, 0.0068],
        [0.0844, 0.3065, 0.0068],
        [0.0844, 0.3065, 0.0068],
        [0.0844, 0.3065, 0.0068],
        [0.0844, 0.3065, 0.0068]])
tensor([0.0844, 0.3065, 0.0068])
